frontend:
  kind: log_mel
  sample_rate: 16000
  n_mels: 40
  window_ms: 30.0
  hop_ms: 10.0
  expected_frames: 98

model:
  name: kwt
  variant: kwt-1
  attention_type: time
  d_model: 64
  num_heads: 2 #1
  depth: 4 #12
  dropout: 0.1
  mlp_dim: 256
  max_frames: 98
  prenorm: false

train:
  #mode: steps
  #max_steps: 23000
  #eval_interval_steps: 1000
  mode: epochs
  max_epochs: 100 #200

  batch_size: 512
  grad_accumulation_steps: 1
  optimizer:
    name: adamw
    lr: 0.001
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.999
  scheduler:
    name: cosine
    #warmup_steps: 2000
    warmup_epochs: 5 #10
    min_lr_ratio: 0.1 #0.1
